theme: jekyll-theme-minimal
logo: https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Ancient_Chinese_instrumentalists.jpg/217px-Ancient_Chinese_instrumentalists.jpg
show_downloads: true

menu_title: "MENU"
menu:
  - title: "Home"
    url: /
  - title: "Results"
    url: /results/  
  - title: "Dataset"
    url: /data/
  - title: "Inspection"
    url: /inspection/
  - title: "Usage"
    url: /usage/
